config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:update]

  resources :charges, only: [:new, :create]

  match "users/:id/downgrade" => "users#downgrade", :as => "downgrade_user", via: [:get, :post]

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  attr_accessor :slug
  belongs_to :user, required: false
  after_initialize :init
  extend FriendlyId
  friendly_id :title, :use => :slugged
  
  private

  def init
    self.private ||= false
  end
end
 

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    if current_user.premium?
      @wikis = Wiki.all
    else
      @wikis = Wiki.where(private: false)
    end
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params.merge(user_id: current_user.id))
    authorize @wiki
    if @wiki.save && current_user.premium?
      @wiki.update_attribute(:private, true)
      flash.now[:notice] = "Your wiki was saved."
      redirect_to @wiki
    elsif @wiki.save
      flash.now[:notice] = "Your wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error, your wiki was not created. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)
    if @wiki.save
       flash.now[:notice] = "Your wiki was updated."
       redirect_to @wiki
    else
      flash.now[:alert] = "Error, your wiki was not updated. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
    def wiki_params
      params.require(:wiki).permit(:title, :body, :user_id)
    end
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/wikis/_edituser.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div id="epiceditor">
  <div class="form-group">
    <% if current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
      </div>
  <% end %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div id="epiceditor">
    <div class="col-md-8">
      <%= render partial: 'wikis/form' %>
    </div>
  </div>
</div>

app/views/wikis/form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/index.html.erb
<div class="container">
<h1>All Wikis</h1>
  <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <p>
          <%= link_to markdown(wiki.title), wiki %>
          <%= markdown(wiki.body) %>
        </p>
      </div>
    </div>
<% end %>
</div>

app/views/wikis/new.html.erb
<%= render partial: 'wikis/form' %>

app/views/wikis/show.html.erb
  <h1><%= markdown(@wiki.title) %></h1>
  <div class="row">
    <div class="col-md-8">
      <p><%= markdown(@wiki.body) %></p>
    </div>
    <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
    </div>
  </div>

app/views/wikis/update.html.erb
<h1>Wiki#update</h1>
<p>Find me in app/views/wiki/update.html.erb</p>