config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:update]

  resources :charges, only: [:new, :create]

  match "users/:id/downgrade" => "users#downgrade", :as => "downgrade_user", via: [:get, :post]

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css" integrity="sha384-v2Tw72dyUXeU3y4aM2Y0tBJQkGfplr39mxZqlTBDUZAb9BGoC40+rdFCG0m10lXk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/fontawesome.css" integrity="sha384-q3jl8XQu1OpdLgGFvNRnPdj5VIlCvgsDQTQB6owSOHWlAurxul7f+JpUOVdAiJ5P" crossorigin="anonymous">
    <script>var editor = new EpicEditor({basePath: '/blocipedia/lib/epiceditor'}).load();</script>
  </head>

  <% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>

  <body>
    <% if user_signed_in? %>
    <p>Signed in as: <strong><%= current_user.email %></strong>
    <%= link_to 'Edit profile', edit_user_registration_path(@user), :class => 'navbar-link' %></p>
    <ul class="nav nav-tabs">
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <li><%= link_to 'View Wikis', wikis_path %></li>
      <li><%= link_to 'Create Wikis', new_wiki_path %></li>
    </ul>
    <% else %>
    <ul class="nav nav-tabs">
      <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
      <li><%= link_to "Sign in", new_user_session_path, :class => 'navbar-link'  %></li>
      <li><%= link_to 'View Wikis', wikis_path %></li>
    </ul>
    <% end %>

      <header class="jumbotron">
        <section >
          <h1 class="text-center">Bloc<span>ipedia</span> / <small>build your <span>wikis</span> for free</small></h1>
        </section>
      </header>
    <%= yield %>
  </body>
</html>